# Generated by Django 4.0.4 on 2022-05-06 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100, verbose_name='Карта')),
                ('birthday', models.DateField()),
                ('last_update', models.DateField()),
                ('pmpk', models.TextField(max_length=300, verbose_name='Заключение ПМПК')),
                ('sound_of_speech', models.TextField(max_length=300, verbose_name='Общее звучание речи')),
                ('structure_and_mobility', models.TextField(max_length=300, verbose_name='Строение и подвижность органов артикуляции')),
                ('understanding', models.TextField(max_length=300, verbose_name='Понимание речи')),
                ('sound_state', models.TextField(max_length=300, verbose_name='Состояние звукопроизношения')),
                ('structure_of_the_word', models.TextField(max_length=300, verbose_name='Слоговая структура слова')),
                ('dictionary_feature', models.TextField(max_length=300, verbose_name='Характеристика словаря')),
                ('grammatical_structure', models.TextField(max_length=300, verbose_name='Грамматический строй речи')),
                ('connected_speech', models.TextField(max_length=300, verbose_name='Связная речь')),
                ('general_recommendations', models.TextField(max_length=500, verbose_name='Рекомендации')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'Информация о пользователях',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField()),
                ('last_update', models.DateField()),
                ('homework', models.TextField(max_length=500, verbose_name='Домашние задание')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
    ]
