# Generated by Django 4.0.4 on 2022-05-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_calendar_cash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='last_update',
        ),
    ]
