# Generated by Django 4.0.4 on 2022-05-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_userinfo_last_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
