# Generated by Django 4.0.4 on 2022-05-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_homework'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
