# Generated by Django 4.0.4 on 2022-05-12 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0007_delete_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, verbose_name='Название занятия')),
                ('duration', models.CharField(max_length=100, verbose_name='Длительность занятия')),
                ('date_of_the_lesson', models.DateTimeField(verbose_name='Дата проведения занятия')),
                ('time_of_the_lesson', models.CharField(max_length=100, verbose_name='Время начала занятия')),
                ('cash', models.IntegerField(verbose_name='Цена')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
    ]
