# Generated by Django 4.0.4 on 2022-05-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_calendar_date_of_the_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(verbose_name='День рождения'),
        ),
    ]
