# Generated by Django 4.0.4 on 2022-05-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_userinfo_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='День рождения'),
        ),
    ]
