# Generated by Django 4.0.4 on 2022-05-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_userinfo_connected_speech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='cash',
            field=models.IntegerField(blank=True, verbose_name='Цена:'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='class_name',
            field=models.CharField(max_length=100, verbose_name='Название занятия:'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='date_of_the_lesson',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения занятия:'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='Длительность занятия:'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Статус:'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='time_of_the_lesson',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время начала занятия:'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='date_of_issue',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания:'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework',
            field=models.TextField(blank=True, max_length=500, verbose_name='Домашние задание:'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework_name',
            field=models.CharField(max_length=100, verbose_name='Название домашнего задания:'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя дата обновления:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='card_name',
            field=models.CharField(max_length=100, verbose_name='Карта:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='connected_speech',
            field=models.TextField(blank=True, max_length=300, verbose_name='Связная речь:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='dictionary_feature',
            field=models.TextField(blank=True, max_length=300, verbose_name='Характеристика словаря:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='general_recommendations',
            field=models.TextField(blank=True, max_length=500, verbose_name='Рекомендации:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='grammatical_structure',
            field=models.TextField(blank=True, max_length=300, verbose_name='Грамматический строй речи:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pmpk',
            field=models.TextField(blank=True, max_length=300, verbose_name='Заключение ПМПК:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sound_of_speech',
            field=models.TextField(blank=True, max_length=300, verbose_name='Общее звучание речи:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sound_state',
            field=models.TextField(blank=True, max_length=300, verbose_name='Состояние звукопроизношения:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='structure_and_mobility',
            field=models.TextField(blank=True, max_length=300, verbose_name='Строение и подвижность органов артикуляции:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='structure_of_the_word',
            field=models.TextField(blank=True, max_length=300, verbose_name='Слоговая структура слова:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='understanding',
            field=models.TextField(blank=True, max_length=300, verbose_name='Понимание речи:'),
        ),
    ]
