# Generated by Django 4.0.4 on 2022-05-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_calendar_cash_alter_calendar_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='cash',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена:'),
        ),
    ]
