# Generated by Django 4.0.4 on 2022-05-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_calendar_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='duration',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Длительность занятия:'),
        ),
    ]
